-- Durable queue and immutable release versions. Only service_role can invoke
-- mutations; browser authorization stays in the Privy-authenticated APIs.
ALTER TABLE public.shelby_projects ADD COLUMN IF NOT EXISTS active_deployment_id uuid,
  ADD COLUMN IF NOT EXISTS desired_deployment_id uuid,
  ADD COLUMN IF NOT EXISTS build_config jsonb NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE public.shelby_deployments DROP CONSTRAINT IF EXISTS shelby_deployments_status_check;
ALTER TABLE public.shelby_deployments ADD CONSTRAINT shelby_deployments_status_check
  CHECK(status IN ('queued','running','ready','succeeded','failed'));
ALTER TABLE public.shelby_deployments ADD COLUMN IF NOT EXISTS pipeline_version integer NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS stage text NOT NULL DEFAULT 'queued',
  ADD COLUMN IF NOT EXISTS failed_stage text,
  ADD COLUMN IF NOT EXISTS error_message text,
  ADD COLUMN IF NOT EXISTS exit_code integer,
  ADD COLUMN IF NOT EXISTS started_at timestamptz,
  ADD COLUMN IF NOT EXISTS finished_at timestamptz,
  ADD COLUMN IF NOT EXISTS duration_ms bigint,
  ADD COLUMN IF NOT EXISTS commit_sha text,
  ADD COLUMN IF NOT EXISTS branch text,
  ADD COLUMN IF NOT EXISTS build_command text,
  ADD COLUMN IF NOT EXISTS build_output text,
  ADD COLUMN IF NOT EXISTS framework text,
  ADD COLUMN IF NOT EXISTS package_manager text,
  ADD COLUMN IF NOT EXISTS shelby_manifest_url text,
  ADD COLUMN IF NOT EXISTS registry_tx_hash text,
  ADD COLUMN IF NOT EXISTS payment_tx_hash text;
ALTER TABLE public.shelby_projects ADD CONSTRAINT shelby_active_deployment_fk FOREIGN KEY(active_deployment_id) REFERENCES public.shelby_deployments(id) ON DELETE SET NULL;
CREATE TABLE public.shelby_build_jobs (
  deployment_id uuid PRIMARY KEY REFERENCES public.shelby_deployments(id) ON DELETE CASCADE,
  project_id uuid NOT NULL REFERENCES public.shelby_projects(id) ON DELETE CASCADE,
  source jsonb NOT NULL, config jsonb NOT NULL,
  env_encrypted jsonb NOT NULL DEFAULT '{}'::jsonb,
  lease_token uuid, lease_until timestamptz, worker_id text,
  event_key text UNIQUE,
  created_at timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.shelby_build_jobs ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.shelby_build_jobs FROM anon, authenticated;
GRANT ALL ON public.shelby_build_jobs TO service_role;
CREATE INDEX shelby_build_queue ON public.shelby_build_jobs(created_at);
ALTER TABLE public.shelby_build_logs ADD COLUMN IF NOT EXISTS sequence bigint GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS stage text;
CREATE INDEX shelby_build_log_cursor ON public.shelby_build_logs(deployment_id, sequence);

-- Earlier migrations used several differently named permissive policies.
-- Clear all browser policies on control-plane tables, not just selected names.
DO $$ DECLARE p record; BEGIN
 FOR p IN SELECT schemaname,tablename,policyname FROM pg_policies WHERE schemaname='public' AND tablename LIKE 'shelby_%'
 LOOP EXECUTE format('DROP POLICY %I ON %I.%I',p.policyname,p.schemaname,p.tablename); END LOOP;
END $$;

CREATE FUNCTION public.shelby_enqueue(p_project uuid,p_owner text,p_source jsonb,p_config jsonb,p_env jsonb,p_event text DEFAULT NULL)
RETURNS uuid LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $$
DECLARE result uuid; pending integer;
BEGIN
 PERFORM 1 FROM public.shelby_projects WHERE id=p_project AND owner_id=p_owner FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Project not found'; END IF;
 IF p_event IS NOT NULL THEN SELECT deployment_id INTO result FROM public.shelby_build_jobs WHERE event_key=p_event; IF result IS NOT NULL THEN RETURN result; END IF; END IF;
 SELECT count(*) INTO pending FROM public.shelby_deployments WHERE project_id=p_project AND status IN ('queued','running');
 IF pending>=3 THEN RAISE EXCEPTION 'Project queue is full (maximum 3 pending builds)'; END IF;
 INSERT INTO public.shelby_deployments(project_id,status,stage,trigger,version_url,content_hash,pipeline_version,branch,commit_sha,message,storage_backend)
 VALUES(p_project,'queued','queued','manual','','',2,p_source->>'branch',p_source->>'commit','Source build queued','pending') RETURNING id INTO result;
 INSERT INTO public.shelby_build_jobs(deployment_id,project_id,source,config,env_encrypted,event_key) VALUES(result,p_project,p_source,p_config,p_env,p_event);
 UPDATE public.shelby_projects SET desired_deployment_id=result,build_config=p_config WHERE id=p_project;
 RETURN result;
END $$;

CREATE FUNCTION public.shelby_claim(p_worker text) RETURNS SETOF public.shelby_build_jobs
LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $$
DECLARE job public.shelby_build_jobs; now_time timestamptz:=clock_timestamp();
BEGIN
 -- An expired attempt is terminal, never silently retried (including payments).
 UPDATE public.shelby_deployments d SET status='failed',failed_stage=d.stage,error_message='Build worker lease expired; inspect logs and redeploy',finished_at=now_time,duration_ms=extract(epoch FROM(now_time-d.started_at))*1000
 FROM public.shelby_build_jobs j WHERE j.deployment_id=d.id AND d.status='running' AND j.lease_until<now_time;
 UPDATE public.shelby_projects p SET status='failed' WHERE p.active_deployment_id IS NULL AND p.content_hash='' AND EXISTS(SELECT 1 FROM public.shelby_deployments d WHERE d.id=p.desired_deployment_id AND d.status='failed');
 -- Serialize claims briefly so two workers cannot lease different jobs for
 -- one project, while SKIP LOCKED still avoids waiting for an occupied row.
 PERFORM pg_advisory_xact_lock(73504192);
 SELECT j.* INTO job FROM public.shelby_build_jobs j JOIN public.shelby_deployments d ON d.id=j.deployment_id
 WHERE d.status='queued' AND NOT EXISTS(SELECT 1 FROM public.shelby_deployments busy WHERE busy.project_id=j.project_id AND busy.status='running')
 ORDER BY j.created_at FOR UPDATE OF j SKIP LOCKED LIMIT 1;
 IF job.deployment_id IS NULL THEN RETURN; END IF;
 UPDATE public.shelby_build_jobs SET lease_token=gen_random_uuid(),lease_until=now_time+interval '180 seconds',worker_id=p_worker WHERE deployment_id=job.deployment_id RETURNING * INTO job;
 UPDATE public.shelby_deployments SET status='running',stage='preparing',started_at=now_time WHERE id=job.deployment_id;
 RETURN NEXT job;
END $$;

CREATE FUNCTION public.shelby_update_job(p_id uuid,p_lease uuid,p_stage text DEFAULT NULL,p_patch jsonb DEFAULT '{}',p_logs jsonb DEFAULT '[]')
RETURNS void LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $$
DECLARE current_stage text; stages text[]:=ARRAY['queued','preparing','cloning','installing','building','validating','uploading','publishing','ready'];
BEGIN
 PERFORM 1 FROM public.shelby_build_jobs j JOIN public.shelby_deployments d ON d.id=j.deployment_id
 WHERE j.deployment_id=p_id AND j.lease_token=p_lease AND j.lease_until>clock_timestamp() AND d.status='running' FOR UPDATE OF j,d;
 IF NOT FOUND THEN RAISE EXCEPTION 'Worker lease is no longer valid'; END IF;
 SELECT stage INTO current_stage FROM public.shelby_deployments WHERE id=p_id;
 IF p_stage IS NOT NULL AND (array_position(stages,p_stage) IS NULL OR array_position(stages,p_stage)<>array_position(stages,current_stage)+1 OR p_stage='ready') THEN RAISE EXCEPTION 'Invalid deployment stage transition'; END IF;
 UPDATE public.shelby_build_jobs SET lease_until=clock_timestamp()+interval '180 seconds' WHERE deployment_id=p_id;
 UPDATE public.shelby_deployments SET stage=coalesce(p_stage,stage),
 framework=coalesce(p_patch->>'framework',framework), package_manager=coalesce(p_patch->>'package_manager',package_manager),
 build_command=coalesce(p_patch->>'build_command',build_command),build_output=coalesce(p_patch->>'build_output',build_output),commit_sha=coalesce(p_patch->>'commit_sha',commit_sha),
 payment_tx_hash=coalesce(p_patch->>'payment_tx_hash',payment_tx_hash),registry_tx_hash=coalesce(p_patch->>'registry_tx_hash',registry_tx_hash)
 WHERE id=p_id;
 INSERT INTO public.shelby_build_logs(project_id,deployment_id,stream,line,level,stage)
 SELECT d.project_id,p_id,l->>'stream',left(l->>'line',65536),CASE WHEN l->>'stream'='stderr' THEN 'error' ELSE 'info' END,coalesce(l->>'stage',current_stage)
 FROM public.shelby_deployments d CROSS JOIN jsonb_array_elements(p_logs) l WHERE d.id=p_id;
END $$;

CREATE FUNCTION public.shelby_fail(p_id uuid,p_lease uuid,p_error text,p_exit integer DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $$
BEGIN
 PERFORM public.shelby_update_job(p_id,p_lease);
 UPDATE public.shelby_deployments SET status='failed',failed_stage=stage,error_message=left(p_error,8000),exit_code=p_exit,finished_at=clock_timestamp(),duration_ms=extract(epoch FROM(clock_timestamp()-started_at))*1000 WHERE id=p_id;
 UPDATE public.shelby_projects SET status='failed' WHERE id=(SELECT project_id FROM public.shelby_deployments WHERE id=p_id) AND active_deployment_id IS NULL AND content_hash='';
END $$;

CREATE FUNCTION public.shelby_publish(p_id uuid,p_lease uuid,p_release jsonb) RETURNS boolean
LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $$
DECLARE d public.shelby_deployments; p public.shelby_projects; promoted boolean;
BEGIN
 -- Lock order matches enqueue/rollback: project before deployment.
 SELECT * INTO p FROM public.shelby_projects WHERE id=(SELECT project_id FROM public.shelby_deployments WHERE id=p_id) FOR UPDATE;
 PERFORM public.shelby_update_job(p_id,p_lease);
 SELECT * INTO d FROM public.shelby_deployments WHERE id=p_id FOR UPDATE;
 IF d.stage<>'publishing' OR d.registry_tx_hash IS NULL OR coalesce(p_release->>'hash','')!~'^[a-f0-9]{64}$' OR coalesce(jsonb_array_length(p_release->'manifest'),0)<1 OR p_release->>'manifestUrl' IS NULL THEN RAISE EXCEPTION 'Release has not passed all publishing requirements'; END IF;
 UPDATE public.shelby_deployments SET status='ready',stage='ready',finished_at=clock_timestamp(),duration_ms=extract(epoch FROM(clock_timestamp()-started_at))*1000,
 content_hash=p_release->>'hash',version_url=p_release->>'versionUrl',storage_backend='shelby',shelby_owner_address=p_release->>'owner',shelby_manifest=p_release->'manifest',shelby_manifest_url=p_release->>'manifestUrl',shelby_uploaded_at=clock_timestamp() WHERE id=p_id;
 promoted:=p.desired_deployment_id=p_id;
 IF promoted THEN
  UPDATE public.shelby_projects SET framework=coalesce(d.framework,framework),build_output=coalesce(d.build_output,build_output),active_deployment_id=p_id,content_hash=p_release->>'hash',latest_version_url=p_release->>'versionUrl',status='live',storage_backend='shelby',shelby_owner_address=p_release->>'owner',shelby_manifest=p_release->'manifest',shelby_uploaded_at=clock_timestamp(),deployed_at=clock_timestamp(),size_bytes=(p_release->>'size')::bigint,files=p_release->'files',registry_tx_hash=d.registry_tx_hash WHERE id=p.id;
  UPDATE public.shelby_domain_mappings SET content_hash=p_release->>'hash' WHERE project_id=p.id;
 END IF;
 RETURN promoted;
END $$;

CREATE FUNCTION public.shelby_rollback(p_project uuid,p_owner text,p_deployment uuid) RETURNS void
LANGUAGE plpgsql SECURITY INVOKER SET search_path='' AS $$
DECLARE d public.shelby_deployments;
BEGIN
 PERFORM 1 FROM public.shelby_projects WHERE id=p_project AND owner_id=p_owner FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Project not found'; END IF;
 SELECT * INTO d FROM public.shelby_deployments WHERE id=p_deployment AND project_id=p_project AND status='ready' AND pipeline_version=2;
 IF NOT FOUND THEN RAISE EXCEPTION 'Ready deployment not found'; END IF;
 UPDATE public.shelby_projects SET framework=coalesce(d.framework,framework),build_output=coalesce(d.build_output,build_output),active_deployment_id=d.id,desired_deployment_id=d.id,content_hash=d.content_hash,latest_version_url=d.version_url,status='live',storage_backend='shelby',shelby_owner_address=d.shelby_owner_address,shelby_manifest=d.shelby_manifest,shelby_uploaded_at=d.shelby_uploaded_at,registry_tx_hash=d.registry_tx_hash,deployed_at=clock_timestamp(),size_bytes=(SELECT coalesce(sum((f->>'size')::bigint),0) FROM jsonb_array_elements(d.shelby_manifest) f),files=(SELECT jsonb_agg(jsonb_build_object('path',f->>'path','name',regexp_replace(f->>'path','^.*/',''),'size',f->'size','type',f->>'type')) FROM jsonb_array_elements(d.shelby_manifest) f) WHERE id=p_project;
 UPDATE public.shelby_domain_mappings SET content_hash=d.content_hash WHERE project_id=p_project;
END $$;

CREATE FUNCTION public.shelby_release_immutable() RETURNS trigger LANGUAGE plpgsql SET search_path='' AS $$
BEGIN
 IF OLD.pipeline_version=2 AND OLD.status IN ('ready','failed') AND NEW IS DISTINCT FROM OLD THEN RAISE EXCEPTION 'Completed deployment versions are immutable'; END IF;
 RETURN NEW;
END $$;
CREATE TRIGGER immutable_release BEFORE UPDATE ON public.shelby_deployments FOR EACH ROW EXECUTE FUNCTION public.shelby_release_immutable();
DO $$ DECLARE f record; BEGIN
 FOR f IN SELECT p.oid::regprocedure AS signature FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname IN ('shelby_enqueue','shelby_claim','shelby_update_job','shelby_fail','shelby_publish','shelby_rollback') LOOP
 EXECUTE format('REVOKE ALL ON FUNCTION %s FROM PUBLIC, anon, authenticated',f.signature);
 EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role',f.signature);
 END LOOP;
END $$;

ALTER TABLE public.shelby_domain_mappings ADD COLUMN IF NOT EXISTS verification_token text;
